version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
    working_directory: /go/src/github.com/janivihervas/devops-tools
    environment:
      - DEP_VERSION: 0.3.2
    steps:
      - checkout
      - run:
          name: Install dep
          command: |
            curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
            chmod +x $GOPATH/bin/dep
      - restore_cache:
          keys:
            - v1-deps-{{ arch }}-{{ checksum "Gopkg.lock" }}
      - run: make install
      - save_cache:
          key: v1-deps-{{ arch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run: make install-tools
      - run: make lint
      - run:
          name: Test
          command: |
            echo "" > coverage.txt
            rm -rf coverage
            mkdir coverage
            parallel -k 'go test -race -coverprofile=coverage/{#}.out -covermode=atomic {}' ::: $(go list ./...)
            find coverage/* -exec cat {} >> coverage.txt \;
            rm -rf coverage
      - run:
          name: Upload coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
