version: 2

references:
  pwd: &pwd
    /go/src/github.com/janivihervas/devops-tools
  env: &env
    docker:
      - image: circleci/golang:1.8.3
    working_directory: *pwd

jobs:
  install:
    <<: *env
    steps:
      - checkout
      - run: make install-vendor
      - run: make install-tools
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - *pwd
  lint:
    <<: *env
    - run: echo $CIRCLE_SHA1 > .circle-sha
    - restore_cache:
        keys:
          - v1-repo-{{ checksum ".circle-sha" }}
    steps:
      - run: pwd
      - run: ls -la
      - run: make lint
  test:
    <<: *env
    - run: echo $CIRCLE_SHA1 > .circle-sha
    - restore_cache:
        keys:
          - v1-repo-{{ checksum ".circle-sha" }}
    steps:
      - run: pwd
      - run: ls -la
      - run: make test
  build-foo:
    <<: *env
    - run: echo $CIRCLE_SHA1 > .circle-sha
    - restore_cache:
        keys:
          - v1-repo-{{ checksum ".circle-sha" }}
    steps:
      - run: pwd
      - run: ls -la
      - run: make build-foo
  build-bar:
    <<: *env
    - run: echo $CIRCLE_SHA1 > .circle-sha
    - restore_cache:
        keys:
          - v1-repo-{{ checksum ".circle-sha" }}
    steps:
      - run: pwd
      - run: ls -la
      - run: make build-bar

workflows:
  version: 2
  ci:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build-foo:
          requires:
            - lint
            - test
      - build-bar:
          requires:
            - lint
            - test
