version: 2

references:
  pwd: &pwd
    /go/src/github.com/janivihervas/devops-tools

  env: &env
    docker:
      - image: circleci/golang:1.8.3
    working_directory: *pwd

  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp

  copy_workspace: &copy_workspace
    run:
      name: Copy workspace
      command: mv /tmp/workspace/* /tmp/workspace/.[!.]* .

jobs:
  install:
    <<: *env
    steps:
      - checkout
      - run: make install-vendor
      - run: make install-tools
      - run: |
            mkdir -p /tmp/workspace
            mv * .[!.]* /tmp/workspace/
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace
  lint:
    <<: *env
    steps:
      - *attach_workspace
      - *copy_workspace
      - run: make lint
  test:
    <<: *env
    steps:
      - *attach_workspace
      - *copy_workspace
      - run: make test
  build-foo:
    <<: *env
    steps:
      - *attach_workspace
      - *copy_workspace
      - run: make build-foo
  build-bar:
    <<: *env
    steps:
      - *attach_workspace
      - *copy_workspace
      - run: make build-bar

workflows:
  version: 2
  ci:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build-foo:
          requires:
            - lint
            - test
      - build-bar:
          requires:
            - lint
            - test
